### ISSUE TITLE
Dead Locks, wehn calling from asp.net website.

### ISSUE THREAD

**Issue by B0R1K** [saguiitay/DropboxRestAPI#1]
It seems to help when i add
ConfigureAwait(false)
return await client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead)
to class HttpClientExtensions

Just wanted to point it out, could be issue on my site as well...

Thank you, so far really like the api

Boris

**Comment by saguiitay** [comment]
Adding ConfigureAwait(false) to all awaits me calls makes sense.
Feel free to send me a PullRequest, or I'll implement it as soon as I can.

**Comment by saguiitay** [comment]
Resolved with commit 69dc9e6123dbf98417957844cf2bae1bc3463b76

**Comment by B0R1K** [comment]
Thank you
