### ISSUE TITLE
previews API call requires root path to be "auto"

### ISSUE THREAD

**Issue by tcuevas92** [saguiitay/DropboxRestAPI#10]
I'm attempting to get the preview for a file by using the PreviewsAsync method. After calling this method I get the error message "Root must be "auto", got "sandbox"". It looks like dropbox requires that you set the root to "auto" when doing the preview call.

**Comment by saguiitay** [comment]
I resolved this in commit fe43da59956637d852a080ac87f888f5240bdfb5

I'll update the NuGet package soon
