### ISSUE TITLE
Cannot force reapproval when requesting an OAuth2 Redirect URI

### ISSUE THREAD

**Issue by AdrianPell** [saguiitay/DropboxRestAPI#17]
When I try to generate a redirect URI as part of the OAuth2 flow, and request reapproval (to force Dropbox to prompt for credentials), I get an error returned on the resulting page:

`"force_reapprove": expecting either "true" or "false", got "True"`

It seems that when the OAuthRequestGenerator generates parameters for the URL it uses the standard (.Net) string representation of `true` ... which is "True".  Apparently, Dropbox doesn't like that.

Happy to generate a PR for that ...

**Comment by saguiitay** [comment]
Released in version 1.1.6
