### ISSUE TITLE
Does not have Save_URL Yet

### ISSUE THREAD

**Issue by hurricanepkt** [saguiitay/DropboxRestAPI#19]
Reference : https://www.dropbox.com/developers/core/docs#save-url

    save_url
    Description
    Save a file from the specified URL into Dropbox. If the given path already exists, the file will be renamed to avoid the conflict (e.g. myfile (1).txt).

I am willing to do a pull request and impliment it myself however there is some design concern about how to handle the return result of the save_url.   It returns a save_url_job which gives the status of the server actions.

**Comment by hurricanepkt** [comment]
My thought is to have the save_url just simply return the save_url_job and let the Consuming Program handle the rest.

**Comment by saguiitay** [comment]
a PR will be great

**Comment by saguiitay** [comment]
Released in version 1.1.6
