### ISSUE TITLE
Delta entries fail to parse

### ISSUE THREAD

**Issue by markhepburn** [saguiitay/DropboxRestAPI#2]
Hi, thanks for this, I really like the API.

I'm using the longpoll_delta + [delta](https://www.dropbox.com/developers/core/docs#delta) combination, and hitting a JSON parsing error.  The Delta response model assumes that the entries is of type [string]; in fact (this might be new, looking at other implementations), it's a 2-element array of [string, metadata].

I have a patch I can try and clean up if you'd like, or you might have your own preferred way of handling it.

**Comment by saguiitay** [comment]
I've implemented a fix for this. I'll commit the changes as soon as I can.

**Comment by saguiitay** [comment]
Resolved with commit 91049cea1abb319b4077d5f8a476f1ecc6a5768b

**Comment by markhepburn** [comment]
Great, thanks!  I just came back to this to open a pull request, great timing (and that looks near-identical to my patch :)).  Thanks again.
