### ISSUE TITLE
include_membership flag on metadata call

### ISSUE THREAD

**Issue by claritytechsolutions** [saguiitay/DropboxRestAPI#4]
Hello, first off this is a great looking API. You've done a great job.

I am having an issue though when passing in the include_membership call when trying to get the membership on a fondler and if never returns any members array. Also the Share_folder attribute does not return either on the metadata call.

is there something i'm calling incorrect?
thanks,
Rob

**Comment by saguiitay** [comment]
Resolved using commit 7f772cd4437d4acc4afbf793ac774738bc38fbe8 and released in version 1.0.5 of the NuGet package
